spring:
  application:
    name: eventflow

  datasource:
    url: jdbc:postgresql://ep-orange-smoke-b5w2ho7n-pooler.c-7.us-east-2.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: "npg_Q0EzDZsPIU2d"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true